AWSTemplateFormatVersion: '2010-09-09'

Description: Stack for custom domain name

Resources:

  SayWhatAPICertificate:
    Type: AWS::CertificateManager::Certificate
    Properties: 
      DomainName: 'api.say-what-app.com'
      Tags:
        Project: say-what

  SayWhatCustomDomain:
    Type: AWS::ApiGatewayV2::DomainName
    Properties: 
      DomainName: api.say-what-app.com
      DomainNameConfigurations:
        CertificateArn: !Ref SayWhatAPICertificate
        EndpointType: REGIONAL
      Tags:
        Project: say-what

  # TODO: Setup base API mapping?

Outputs:

  SayWhatCustomDomainName:
    Description: Custom domain name for API
    Value: !Ref SayWhatCustomDomain