AWSTemplateFormatVersion: '2010-09-09'

Description: Stack for custom domain name

Resources:

  SayWhatAPICertificate:
    Type: AWS::CertificateManager::Certificate
    Properties: 
      DomainName: 'api.say-what-app.com'      

  SayWhatCustomDomain:
    Type: AWS::ApiGatewayV2::DomainName
    Properties: 
      DomainName: api.say-what-app.com
      DomainNameConfigurations:
        CertificateArn: !Ref SayWhatAPICertificate
        EndpointType: REGIONAL

  Outputs:
    SayWhatCustomDomainName:
      Description: Custom domain name for API
      Value: !Ref SayWhatCustomDomain