AWSTemplateFormatVersion: '2010-09-09'

Description: Stack for custom domain name

Parameters:
  DomainNameParameter:
    Type: String
    Default: 'api.say-what-app.com'
  HostedZoneIdParameter:
    Type: String

Resources:

  SayWhatAPICertificate:
    Type: AWS::CertificateManager::Certificate
    Properties: 
      DomainName: !Ref DomainNameParameter
      DomainValidationOptions:
        - DomainName: !Ref DomainNameParameter
          HostedZoneId: !Ref HostedZoneIdParameter
      Tags:
        - Key: Project
          Value: saywhat

  SayWhatCustomDomain:
    Type: AWS::ApiGatewayV2::DomainName
    Properties: 
      DomainName: api.say-what-app.com
      DomainNameConfigurations:
        - CertificateArn: !Ref SayWhatAPICertificate
          EndpointType: REGIONAL
      Tags:
        Project: saywhat # All other reasources seem to have this as an array but here it's map for some reason

  # TODO: Setup base API mapping?

Outputs:

  SayWhatCustomDomainName:
    Description: Custom domain name for API
    Value: !Ref SayWhatCustomDomain
