
AWSTemplateFormatVersion: 2010-09-09

Resources: 

  SayWhatUserTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: username
          AttributeType: S
        - AttributeName: name
          AttributeType: S
        - AttributeName: passwordHash
          AttributeType: S
      KeySchema: 
        - AttributeName: username
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: SayWhatUsers

Outputs:

  SayWhatUserTableArn:
    Description: ARN of table of users
    Value: !GetAtt SayWhatUserTable.Arn

  SayWhatUserTableName:
    Description: Name of table of users
    Value: !Ref SayWhatUserTable
      
         