# This workflow will deploy to AWS

name: Deploy to AWS

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:12-alpine

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install CLI dependencies
      run: |
        apk add zip python3 py3-pip && pip3 install --upgrade pip && pip3 install awscli

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
      
    # https://github.com/aws-actions/aws-cloudformation-github-deploy
    - name: Deploy S3 CodeFile Bucket
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: saywhat-s3-codefile-bucket
        template: ./cloudformation/s3-codefile-bucket.yml
        no-fail-on-empty-changeset: "1"

    - name: Deploy API Custom Domain Name
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: saywhat-api-custom-dns
        template: ./cloudformation/api-custom-dns.yml
        no-fail-on-empty-changeset: "1"
        # AWS_HOSTED_ZONE_ID is extracted from the Route53 console
        parameter-overrides: "HostedZoneIdParameter=${{ secrets.AWS_HOSTED_ZONE_ID }}"

    - name: Deploy DynamoDB Question Table
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: saywhat-dynamodb-question-table
        template: ./cloudformation/dynamodb-question-table.yml
        no-fail-on-empty-changeset: "1"