# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:12-alpine

    strategy:
      matrix:
        node-version: [12.x]

    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        env:
          SERVICES: dynamodb
          DEFAULT_REGION: eu-west-1
          DOCKER_HOST: unix:///var/run/docker.sock
        options: --name localstack

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Build and test
      env:
        ENVIRONMENT: pipeline
      run: |
        npm ci
        npm run build --if-present
        npm test
